### PR TITLE
added May data files and read w/ Jupyter notebook

### PR DESCRIPTION
**Pull request by deszoeke**
Probably should create a new folder.

Protoype reader doesn't follow CookieCutter path conventions. Everything is just right in `/code`.

Any need to separate julia/python/matlab code?

### CODE REVIEW

**Comment by deszoeke** [comment]
boiler plate missing for tests.

**Comment by jtomfarrar** [comment]
My cookiecutter template is a work in progress.  I actually tried to get rid of all of the tests.  The template I originally cloned had them (https://github.com/jbusecke/cookiecutter-science-project).  I have been gradually editing the template to be more of a bare bones repo that incorporates some best practices for reproducible science.

**Comment by jtomfarrar** [comment]
> 



> Any need to separate julia/python/matlab code?

I would say not now.  We could do it later if needed.

**Comment by deszoeke** [comment]
i couldn't (figure out how to) make new folders in the github repo. i guess that makes sense since it's a clonable diffable version of a repo that each of us could have on our local pc. so "refactoring" directories in a git repo is another unknown for me.

i don't understand the 4 generations of data. perhaps it accommodates some good data mgmt practices. if revising paths, one can migrate from little data-adjacent reader codes to libraries of higher level analysis on more organized and refined data sets. like i said though, i don't know how to revise the paths.
________________________________

**Pull request merged**
